# Generated by Django 3.1.3 on 2020-12-18 10:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=200, unique=True)),
            ],
            options={
                'verbose_name_plural': 'CATEGORY',
            },
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('image', models.ImageField(default='default-user.png', upload_to='customers_pics')),
                ('phone', models.CharField(max_length=11)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('group', models.CharField(choices=[('WHOLESALER', 'WHOLESALER'), ('AGENT', 'AGENT'), ('BOOKSHOP', 'BOOKSHOP'), ('SPECIALIZED CUSTOMER', 'SPECIALIZED CUSTOMER'), ('RETAIL', 'RETAIL'), ('SCHOOL', 'SCHOOL'), ('OTHERS', 'OTHERS')], max_length=100)),
                ('discount', models.IntegerField(blank=True, choices=[(5, 5), (10, 10), (15, 15), (20, 20), (25, 25), (30, 30), (35, 35), (40, 40), (45, 45), (50, 50), (100, 100)], default=0, null=True)),
                ('date_joined', models.DateTimeField(auto_now_add=True)),
                ('amount_paid', models.IntegerField(blank=True, default='0', null=True)),
                ('last_updated', models.DateTimeField(null=True)),
            ],
            options={
                'verbose_name_plural': 'CUSTOMERS',
            },
        ),
        migrations.CreateModel(
            name='CustomerHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('book_received', models.CharField(max_length=300)),
                ('book_price', models.PositiveIntegerField(blank=True, default='0', null=True)),
                ('quantity_collected', models.PositiveIntegerField(blank=True, default='0', null=True)),
                ('total_cost_price', models.PositiveIntegerField(blank=True, default='0', null=True)),
                ('discount', models.IntegerField(blank=True, choices=[(5, 5), (10, 10), (15, 15), (20, 20), (25, 25), (30, 30), (35, 35), (40, 40), (45, 45), (50, 50), (100, 100)], default=0, null=True)),
                ('amount_paid', models.IntegerField(blank=True, default='0', null=True)),
                ('last_updated', models.DateTimeField(auto_now=True, null=True)),
            ],
            options={
                'verbose_name_plural': "CUSTOMER'S HISTORY",
            },
        ),
        migrations.CreateModel(
            name='StockHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(blank=True, max_length=50, null=True)),
                ('quantity', models.IntegerField(blank=True, default='0', null=True)),
                ('price', models.IntegerField(default='0')),
                ('receive_quantity', models.IntegerField(blank=True, default='0', null=True)),
                ('receive_by', models.CharField(blank=True, max_length=50, null=True)),
                ('receive_from', models.CharField(blank=True, max_length=100, null=True)),
                ('receive_cost', models.IntegerField(blank=True, default='0', null=True)),
                ('issue_quantity', models.IntegerField(blank=True, default='0', null=True)),
                ('issue_by', models.CharField(blank=True, max_length=50, null=True)),
                ('issue_cost', models.IntegerField(blank=True, default='0', null=True)),
                ('amount_paid', models.IntegerField(blank=True, default='0', null=True)),
                ('phone_number', models.CharField(blank=True, max_length=50, null=True)),
                ('created_by', models.CharField(blank=True, max_length=50, null=True)),
                ('reorder_level', models.IntegerField(blank=True, default='0', null=True)),
                ('last_updated', models.DateTimeField(null=True)),
                ('export_to_CSV', models.BooleanField(default=False)),
                ('timestamp', models.DateTimeField(null=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='management.category')),
                ('issue_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='management.customer')),
            ],
            options={
                'verbose_name_plural': 'STOCK HISTORY',
                'ordering': ['-last_updated'],
            },
        ),
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='books')),
                ('item_name', models.CharField(blank=True, max_length=50, null=True)),
                ('quantity', models.IntegerField(blank=True, default='0', null=True)),
                ('price', models.IntegerField(default='0')),
                ('receive_quantity', models.IntegerField(blank=True, default='0', null=True)),
                ('receive_by', models.CharField(blank=True, max_length=50, null=True)),
                ('receive_from', models.CharField(blank=True, max_length=100, null=True)),
                ('receive_cost', models.IntegerField(blank=True, default='0', null=True)),
                ('issue_quantity', models.IntegerField(blank=True, default='0', null=True)),
                ('issue_by', models.CharField(blank=True, max_length=50, null=True)),
                ('issue_cost', models.IntegerField(blank=True, default='0', null=True)),
                ('phone_number', models.CharField(blank=True, max_length=50, null=True)),
                ('created_by', models.CharField(blank=True, max_length=50, null=True)),
                ('reorder_level', models.IntegerField(blank=True, default='0', null=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('export_to_CSV', models.BooleanField(default=False)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('amount_paid', models.IntegerField(blank=True, default='0', null=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='management.category')),
                ('issue_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='management.customer')),
            ],
            options={
                'verbose_name_plural': 'BOOKS',
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.CharField(blank=True, max_length=500)),
                ('ip', models.CharField(blank=True, max_length=20)),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'CHAT',
            },
        ),
    ]
