# Generated by Django 3.1.3 on 2020-12-13 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0002_auto_20201212_2132'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='amount_paid',
            field=models.IntegerField(blank=True, default='0', null=True),
        ),
        migrations.AddField(
            model_name='stockhistory',
            name='amount_paid',
            field=models.IntegerField(blank=True, default='0', null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='group',
            field=models.CharField(choices=[('RETAIL', 'RETAIL'), ('BOOKSHOP', 'BOOKSHOP'), ('OTHERS', 'OTHERS'), ('AGENT', 'AGENT'), ('SPECIALIZED CUSTOMER', 'SPECIALIZED CUSTOMER'), ('SCHOOL', 'SCHOOL'), ('WHOLESALER', 'WHOLESALER')], max_length=100),
        ),
        migrations.AlterField(
            model_name='customerhistory',
            name='group',
            field=models.CharField(choices=[('RETAIL', 'RETAIL'), ('BOOKSHOP', 'BOOKSHOP'), ('OTHERS', 'OTHERS'), ('AGENT', 'AGENT'), ('SPECIALIZED CUSTOMER', 'SPECIALIZED CUSTOMER'), ('SCHOOL', 'SCHOOL'), ('WHOLESALER', 'WHOLESALER')], max_length=100),
        ),
    ]
