# Generated by Django 3.1.3 on 2020-12-13 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0003_auto_20201212_2139'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='group',
            field=models.CharField(choices=[('OTHERS', 'OTHERS'), ('SCHOOL', 'SCHOOL'), ('AGENT', 'AGENT'), ('RETAIL', 'RETAIL'), ('BOOKSHOP', 'BOOKSHOP'), ('SPECIALIZED CUSTOMER', 'SPECIALIZED CUSTOMER'), ('WHOLESALER', 'WHOLESALER')], max_length=100),
        ),
        migrations.AlterField(
            model_name='customerhistory',
            name='book_received',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='customerhistory',
            name='group',
            field=models.CharField(choices=[('OTHERS', 'OTHERS'), ('SCHOOL', 'SCHOOL'), ('AGENT', 'AGENT'), ('RETAIL', 'RETAIL'), ('BOOKSHOP', 'BOOKSHOP'), ('SPECIALIZED CUSTOMER', 'SPECIALIZED CUSTOMER'), ('WHOLESALER', 'WHOLESALER')], max_length=100),
        ),
    ]
