# Generated by Django 3.1.3 on 2020-12-13 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0004_auto_20201212_2150'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='group',
            field=models.CharField(choices=[('SCHOOL', 'SCHOOL'), ('BOOKSHOP', 'BOOKSHOP'), ('OTHERS', 'OTHERS'), ('AGENT', 'AGENT'), ('WHOLESALER', 'WHOLESALER'), ('SPECIALIZED CUSTOMER', 'SPECIALIZED CUSTOMER'), ('RETAIL', 'RETAIL')], max_length=100),
        ),
        migrations.AlterField(
            model_name='customerhistory',
            name='book_received',
            field=models.CharField(default='Biology', max_length=300),
        ),
        migrations.AlterField(
            model_name='customerhistory',
            name='group',
            field=models.CharField(choices=[('SCHOOL', 'SCHOOL'), ('BOOKSHOP', 'BOOKSHOP'), ('OTHERS', 'OTHERS'), ('AGENT', 'AGENT'), ('WHOLESALER', 'WHOLESALER'), ('SPECIALIZED CUSTOMER', 'SPECIALIZED CUSTOMER'), ('RETAIL', 'RETAIL')], max_length=100),
        ),
    ]
