# Generated by Django 3.1.3 on 2020-12-13 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0005_auto_20201212_2150'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerhistory',
            name='debt',
            field=models.PositiveIntegerField(blank=True, default='0', null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='group',
            field=models.CharField(choices=[('SPECIALIZED CUSTOMER', 'SPECIALIZED CUSTOMER'), ('BOOKSHOP', 'BOOKSHOP'), ('WHOLESALER', 'WHOLESALER'), ('OTHERS', 'OTHERS'), ('RETAIL', 'RETAIL'), ('AGENT', 'AGENT'), ('SCHOOL', 'SCHOOL')], max_length=100),
        ),
        migrations.AlterField(
            model_name='customerhistory',
            name='book_received',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='customerhistory',
            name='group',
            field=models.CharField(choices=[('SPECIALIZED CUSTOMER', 'SPECIALIZED CUSTOMER'), ('BOOKSHOP', 'BOOKSHOP'), ('WHOLESALER', 'WHOLESALER'), ('OTHERS', 'OTHERS'), ('RETAIL', 'RETAIL'), ('AGENT', 'AGENT'), ('SCHOOL', 'SCHOOL')], max_length=100),
        ),
        migrations.AlterField(
            model_name='customerhistory',
            name='last_updated',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
