# Generated by Django 3.1.3 on 2020-12-13 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0007_auto_20201212_2227'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerhistory',
            name='quantity_collected',
            field=models.PositiveIntegerField(blank=True, default='0', null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='group',
            field=models.CharField(choices=[('RETAIL', 'RETAIL'), ('BOOKSHOP', 'BOOKSHOP'), ('SCHOOL', 'SCHOOL'), ('AGENT', 'AGENT'), ('SPECIALIZED CUSTOMER', 'SPECIALIZED CUSTOMER'), ('WHOLESALER', 'WHOLESALER'), ('OTHERS', 'OTHERS')], max_length=100),
        ),
    ]
