# Generated by Django 3.1.3 on 2020-12-13 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0008_auto_20201212_2231'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customerhistory',
            name='phone',
        ),
        migrations.AlterField(
            model_name='customer',
            name='group',
            field=models.CharField(choices=[('AGENT', 'AGENT'), ('WHOLESALER', 'WHOLESALER'), ('SCHOOL', 'SCHOOL'), ('SPECIALIZED CUSTOMER', 'SPECIALIZED CUSTOMER'), ('RETAIL', 'RETAIL'), ('OTHERS', 'OTHERS'), ('BOOKSHOP', 'BOOKSHOP')], max_length=100),
        ),
    ]
