# Generated by Django 3.1.3 on 2020-12-13 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0009_auto_20201212_2245'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerhistory',
            name='book_price',
            field=models.PositiveIntegerField(blank=True, default='0', null=True),
        ),
        migrations.AddField(
            model_name='customerhistory',
            name='total_cost_price',
            field=models.PositiveIntegerField(blank=True, default='0', null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='group',
            field=models.CharField(choices=[('BOOKSHOP', 'BOOKSHOP'), ('RETAIL', 'RETAIL'), ('WHOLESALER', 'WHOLESALER'), ('AGENT', 'AGENT'), ('SPECIALIZED CUSTOMER', 'SPECIALIZED CUSTOMER'), ('SCHOOL', 'SCHOOL'), ('OTHERS', 'OTHERS')], max_length=100),
        ),
    ]
