# Generated by Django 3.1.3 on 2020-12-16 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0011_auto_20201215_2150'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customerhistory',
            name='paying',
        ),
        migrations.AddField(
            model_name='customer',
            name='discount',
            field=models.IntegerField(blank=True, default='0', null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='group',
            field=models.CharField(choices=[('OTHERS', 'OTHERS'), ('BOOKSHOP', 'BOOKSHOP'), ('WHOLESALER', 'WHOLESALER'), ('RETAIL', 'RETAIL'), ('SCHOOL', 'SCHOOL'), ('AGENT', 'AGENT'), ('SPECIALIZED CUSTOMER', 'SPECIALIZED CUSTOMER')], max_length=100),
        ),
    ]
