# Generated by Django 3.1.3 on 2020-12-16 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0012_auto_20201216_0029'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerhistory',
            name='discount',
            field=models.IntegerField(blank=True, choices=[(5, 5), (10, 10), (15, 15), (20, 20), (25, 25), (30, 30), (35, 35), (40, 40), (45, 45), (50, 50), (100, 100)], null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='discount',
            field=models.IntegerField(blank=True, choices=[(5, 5), (10, 10), (15, 15), (20, 20), (25, 25), (30, 30), (35, 35), (40, 40), (45, 45), (50, 50), (100, 100)], null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='group',
            field=models.CharField(choices=[('WHOLESALER', 'WHOLESALER'), ('AGENT', 'AGENT'), ('BOOKSHOP', 'BOOKSHOP'), ('SPECIALIZED CUSTOMER', 'SPECIALIZED CUSTOMER'), ('RETAIL', 'RETAIL'), ('SCHOOL', 'SCHOOL'), ('OTHERS', 'OTHERS')], max_length=100),
        ),
    ]
