# Generated by Django 3.1.3 on 2020-12-17 04:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0013_auto_20201216_0143'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='discount',
            field=models.IntegerField(blank=True, choices=[(5, 5), (10, 10), (15, 15), (20, 20), (25, 25), (30, 30), (35, 35), (40, 40), (45, 45), (50, 50), (100, 100)], default=0, null=True),
        ),
        migrations.AlterField(
            model_name='customerhistory',
            name='discount',
            field=models.IntegerField(blank=True, choices=[(5, 5), (10, 10), (15, 15), (20, 20), (25, 25), (30, 30), (35, 35), (40, 40), (45, 45), (50, 50), (100, 100)], default=0, null=True),
        ),
        migrations.CreateModel(
            name='Summary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('summary', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='management.customerhistory')),
            ],
            options={
                'verbose_name_plural': 'SUMMARY',
            },
        ),
    ]
