# Generated by Django 3.1.3 on 2020-12-17 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0014_auto_20201216_1604'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerhistory',
            name='summary_total',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.RemoveField(
            model_name='summary',
            name='summary',
        ),
        migrations.AddField(
            model_name='summary',
            name='summary',
            field=models.ManyToManyField(to='management.CustomerHistory'),
        ),
    ]
