# Generated by Django 3.1.3 on 2020-12-17 09:09

from django.db import migrations, models
import management.models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0015_auto_20201216_2047'),
    ]

    operations = [
        migrations.AddField(
            model_name='summary',
            name='total_amount_received',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='summary',
            name='summary',
            field=models.ManyToManyField(default=management.models.CustomerHistory, to='management.CustomerHistory'),
        ),
    ]
