# Generated by Django 3.1.3 on 2020-12-17 09:21

from django.db import migrations, models
import django.db.models.deletion
import management.models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0016_auto_20201216_2109'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='summary',
            name='summary',
        ),
        migrations.AddField(
            model_name='summary',
            name='summary',
            field=models.ForeignKey(default=management.models.CustomerHistory, on_delete=django.db.models.deletion.CASCADE, to='management.customerhistory'),
        ),
    ]
