# Generated by Django 3.1.3 on 2020-12-17 09:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0018_auto_20201216_2121'),
    ]

    operations = [
        migrations.AlterField(
            model_name='summary',
            name='summary',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='management.customerhistory'),
        ),
    ]
