# Generated by Django 3.1.3 on 2020-12-17 09:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0020_auto_20201216_2123'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Summary',
        ),
    ]
