# Generated by Django 3.1.3 on 2020-12-18 07:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0021_delete_summary'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customerhistory',
            name='summary_total',
        ),
    ]
